const actions = {
    SELECT_BFS: 'SELECT_BFS',
    SELECT_DFS: 'SELECT_DFS',
    SELECT_DIJKSTRA: 'SELECT_DIJKSTRA',
    SELECTION: 'SELECTION',
    NO_SELECTION: 'NO_SELECTION',
    ANIMATION_START: 'ANIMATION_START',
    ANIMATION_END: 'ANIMATION_END',
}
export default actions;