const actions = {
    SELECT_BFS: 'SELECT_BFS',
    SELECT_DFS: 'SELECT_DFS',
    SELECT_DIJKSTRA: 'SELECT_DIJKSTRA',
    SELECT_KRUSKAL: 'SELECT_KRUSKAL',
    SELECT_PRIM: 'SELECT_PRIM',
    SELECT_HEAP: 'SELECT_HEAP',
    SELECT_AVL: 'SELECT_AVL',
    SELECTION: 'SELECTION',
    NO_SELECTION: 'NO_SELECTION',
    ANIMATION_START: 'ANIMATION_START',
    ANIMATION_END: 'ANIMATION_END',
    CLEAR_GRAPH: 'CLEAR_GRAPH',

    INC_SPEED: 'INC_SPEED',
    DEC_SPEED: 'DEC_SPEED',
    CHANGE_SPEED: 'CHANGE_SPEED',
}
export default actions;